# -*- coding: utf-8 -*-
"""visual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/gwynx23/db2b88dca1f521a93385031984581fae/visual.ipynb
"""

import networkx as nx
import matplotlib.pyplot as plt

def visualize_graph():
    G = nx.Graph()

    edges = [(0, 1, 2), (0, 3, 6), (1, 2, 3), (1, 4, 5), (2, 4, 7), (3, 4, 9)]
    G.add_weighted_edges_from(edges)

    pos = nx.spring_layout(G)  # Layout for visualization
    nx.draw(G, pos, with_labels=True, node_color='lightgreen', node_size=500, font_size=10, font_weight='bold')
    labels = nx.get_edge_attributes(G, 'weight')
    nx.draw_networkx_edge_labels(G, pos, edge_labels=labels)

    plt.title('Water Distribution Network (Dijkstra’s Algorithm)')
    plt.show()

visualize_graph()

"""# New Section"""